name: 'Committer'
description: ''
inputs:
  GITHUB_TOKEN:
    description: 'github token used to auth to ghcr'
    required: true
  GITHUB_ACTOR:
    description: 'github actor used to commit as'
    required: true
  GITHUB_ACTOR_EMAIL:
    description: 'github actor used to commit as'
    required: true
  DIRECTORIES:
    description: 'csv of directory globs to git add by default its entire repo'
    default: '.'
    required: false
  BRANCH_NAME:
    description: 'branch to make a pr on'
    required: false
  PARENT_BRANCH_NAME:
    description: 'branch to make pr merge into'
    required: false
  GPG_PRIVATE_KEY:
    description: 'GPG key to sign commits with'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set Git user
      shell: bash
      run: |
        echo "${{ inputs.GPG_PRIVATE_KEY }}"  > /tmp/gpg_key
        gpg --import /tmp/gpg_key
        git config --global user.name "${{inputs.GITHUB_ACTOR}}"
        git config --global user.email "${{inputs.GITHUB_ACTOR_EMAIL}}"
        git config --global commit.gpgsign "1"
        git config --global --add url."https://${{ inputs.GITHUB_TOKEN }}:x-oauth-basic@github".insteadOf ssh://git@github
        git config --global --add url."https://${{ inputs.GITHUB_TOKEN }}:x-oauth-basic@github".insteadOf https://github
        git config --global --add url."https://${{ inputs.GITHUB_TOKEN }}:x-oauth-basic@github".insteadOf git@github
    - name: Commit and Push Changes
      shell: bash
      run: |
        if [[ "${{inputs.BRANCH_NAME}}" != "" ]]; then
          git checkout -b ${{inputs.BRANCH_NAME}}
        fi
        git add -A ${{inputs.DIRECTORIES}}
        if [[ `git status --porcelain` ]]; then
          git commit -m "Automatically added GitHub issue links to TODOs"
          if [[ "${{inputs.BRANCH_NAME}}" != "" ]]; then
            git push --set-upstream origin ${{inputs.BRANCH_NAME}}
            gh pr create --base ${{ inputs.PARENT_BRANCH_NAME }} --head ${{inputs.BRANCH_NAME}} --title "${{inputs.BRANCH_NAME}}" --body "${{inputs.BRANCH_NAME}}"
          else
            git push
          fi
        else
          echo "No changes to commit"
        fi
