#PARTIAL#
#REPOSITORY_MATCH discovery-service,ecr-retagger,federationmanager,idp,image-scanner,kubeval-tools,lambda-promtail,oidc_relying_party_example,publish_app,puppeteer-tester,rapid-connector,rapid-idp-manager,reporting-service,shib-sp,validator-service,verifid #
name: Approve
on:
  issue_comment:
    types: [created]
jobs:
  all:
    permissions:
      id-token: write
      contents: read
      statuses: write
      issues: read
      pull-requests: write
    secrets:
      REPO_SCOPED_TOKEN: ${{secrets.ALL_REPO_SCOPED_TOKEN_2}}
    uses: ausaccessfed/workflows/.github/workflows/approve.yml@main
    with:
      event_name: ${{ github.event_name }}
      event_comment_id: ${{ github.event.comment.id }}
      event_comment_body: ${{ github.event.comment.body }}
