#PARTIAL#
#REPOSITORY_MATCH discovery-service,federationmanager,oidc_relying_party_example,rapid-connector,rapid-idp-manager,reporting-service,shib-sp,validator-service,verifid #
name: Sync development
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN"

jobs:
  call-development-sync:
    concurrency:
      group: sync-development
      cancel-in-progress: true
    uses: ausaccessfed/workflows/.github/workflows/sync-development.yml@main
    with:
