#PARTIAL#
#REPOSITORY_MATCH discovery-service,federationmanager,oidc_relying_party_example,rapid-connector,rapid-idp-manager,reporting-service,shib-sp,validator-service,verifid #
name: Sync development
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  call-development-sync:
    concurrency:
      group: sync-development
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - uses: ausaccessfed/workflows/.github/actions/sync-development@main
        with:
          SHA: ${{ github.sha }}
          ROLE: ${{ secrets.ROLE }}
