name: 'Validate gpg key'
description: ''
inputs:
  BRANCH_NAME:
    description: 'branch to checkout'
    default: ''
  CHECK_TRUSTED:
    description: 'Check if user is trusted'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - uses: ausaccessfed/workflows/.github/actions/init@main
      with:
        FETCH_DEPTH: '0'
        BRANCH_NAME: 'main'
        REPOSITORY: 'ausaccessfed/workflows'

    - name: Verify user as trusted
      if: inputs.CHECK_TRUSTED == 'true'
      shell: bash
      run: |
        cat trusted_keys/trusted_auto_approvers | grep "${{github.actor}}"

    - name: Copy source
      shell: bash
      id: copy-source
      run: |
        mkdir ../temp
        cp -r scripts/verify_commit.sh ../temp/verify_commit.sh
        cp -r trusted_keys ../temp/trusted_keys

    - uses: ausaccessfed/workflows/.github/actions/init@main
      with:
        BRANCH_NAME: ${{ inputs.BRANCH_NAME }}

    - name: Verify Commit
      shell: bash
      id: verify-commit
      run: |
        cp ../temp/verify_commit.sh verify_commit.sh
        cp -r ../temp/trusted_keys trusted_keys
        bash verify_commit.sh ${{ inputs.BRANCH_NAME }}
