name: 'Validate gpg key'
description: ''
inputs:
  BRANCH_NAME:
    description: 'branch to checkout'
    default: ''
  CHECK_TRUSTED:
    description: 'Check if user is trusted'
    default: 'false'
  GITHUB_TOKEN:
    description: 'github token used to auth to api'
    default: ''
  HEAD_SHA:
    description: 'head sha of commit that triggered this workflow'
    default: ''
  STATUS_CONTEXT:
    description: 'context for the commit status to be updated if the verification fails'
    default: ''
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        mkdir ../temp

        BASE_URL="https://raw.githubusercontent.com/ausaccessfed/workflows/main"
        FILE_LIST=$(curl -sSL "$BASE_URL/trusted_keys/index.txt")
        for FILE in "${FILE_LIST[@]}"; do
          curl -sSL "$BASE_URL/trusted_keys/$FILE" -o "../temp/trusted_keys/$FILE"
        done

        curl -sSL "$BASE_URL/scripts/verify_commit.sh" -o ../temp/verify_commit.sh

    - name: Verify user as trusted
      if: inputs.CHECK_TRUSTED == 'true'
      shell: bash
      run: |
        cat trusted_keys/trusted_self_approvers | grep "${{github.actor}}"

    - uses: ausaccessfed/workflows/.github/actions/init@main
      with:
        BRANCH_NAME: ${{ inputs.BRANCH_NAME }}

    - name: Verify Commit
      shell: bash
      id: verify-commit
      run: |
        cp ../temp/verify_commit.sh verify_commit.sh
        cp -r ../temp/trusted_keys trusted_keys
        bash verify_commit.sh ${{ inputs.BRANCH_NAME }}

    - name: Set commit status
      if: steps.verify-commit.outcome == 'failure' && inputs.HEAD_SHA != ''
      uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
      with:
        sha: ${{ inputs.HEAD_SHA }}
        token: ${{ inputs.GITHUB_TOKEN }}
        status: failure
        description: 'Verify Commit step failed'
        context: inputs.STATUS_CONTEXT
