name: 'Branch finder'
description: ''
inputs:
  EVENT_NAME:
    description: 'event type'
    required: true
outputs:
  BRANCH_NAME:
    value: ${{ steps.branch.outputs.BRANCH_NAME }}
    description: 'The branch name determined by the action'
runs:
  using: 'composite'
  steps:
    - uses: xt0rted/pull-request-comment-branch@e8b8daa837e8ea7331c0003c9c316a64c6d8b0b1 # v3.0.0
      if: inputs.EVENT_NAME == 'issue_comment'
      id: comment-branch

    - id: branch
      shell: bash
      name: set branch
      run: |
        ## PR comment branch || pr branch || default branch
        if [ "${{ steps.comment-branch.outputs.head_ref }}" != "" ]; then
          BRANCH_NAME="${{ steps.comment-branch.outputs.head_ref }}"
        elif [ "${{ github.head_ref }}" != "" ]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME="${{ github.ref_name }}"
        fi
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
