name: 'Update manifest'
description: ''
inputs:
  BRANCH_NAME:
    description: 'branch to checkout'
    default: ''
  ROLE:
    description: 'aws role to be used'
    default: ''
  ECR_REPOSITORY:
    description: 'ecr repository to login to'
    default: ''
  GITHUB_TOKEN:
    description: 'github token used to auth to ghcr'
    default: ''
  GITHUB_ACTOR:
    description: 'github actor used to auth to ghcr'
    default: ''
  IMAGE_TAGS:
    description: 'tags to be merged with -t'
    required: true
  IMAGE_TAG_SOURCE:
    description: 'tags to be merged'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

    - uses: ausaccessfed/workflows/.github/actions/init@main
      with:
        BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
        ROLE: ${{ inputs.ROLE }}
        ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ inputs.GITHUB_ACTOR }}

    - name: Download digests
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        path: /tmp/digests
        pattern: digests-*
        merge-multiple: true

    - name: Create and push manifest list
      shell: bash
      run: |
        IMAGE_TAGS="$(echo "${{inputs.IMAGE_TAGS}}" | sed 's/~/\n/g' | sed -e 's/^/-t /')"
        docker buildx imagetools create \
          $IMAGE_TAGS \
          $(printf '${{ inputs.IMAGE_TAG_SOURCE }}@sha256:%s ' $(ls /tmp/digests)) \
    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ inputs.IMAGE_TAG_SOURCE }}
