name: 'Renovate Dependency Check'
description: ''
inputs:
  FORCE_RECREATE:
    description: 'If you should recreate all prs (this is break glass)'
    required: false
    default: 'false'
  LOG_LEVEL:
    description: 'Log level'
    default: 'info'
  ROLE:
    description: 'AWS role to assume'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  GPG_PRIVATE_KEY:
    description: 'GPG key to sign commits with'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ausaccessfed/workflows/.github/actions/branch_finder@main
      id: branch
      with:
        EVENT_NAME: ${{ github.event_name }}

    - uses: ausaccessfed/workflows/.github/actions/init@main
      with:
        ROLE: ${{ inputs.ROLE }}
        BRANCH_NAME: ${{ steps.branch.outputs.BRANCH_NAME }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: vars
      shell: bash
      id: vars
      run: |
        RECREATE_PRS=$([ "${{ inputs.FORCE_RECREATE }}" == "true" ] && echo "always" || echo "auto")
        echo "RECREATE_PRS=$RECREATE_PRS" >> $GITHUB_OUTPUT

    - name: Renovate
      uses: renovatebot/github-action@70ea19f1b0dc8a9cc7af1b4278f8d3fd9778b577 # v43.0.17
      with:
        configurationFile: .github/renovate-config.js
        token: ${{ inputs.GITHUB_TOKEN }}
        env-regex: ^(?:RENOVATE_\w+|AWS_\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|(?:HTTPS?|NO)_PROXY|(?:https?|no)_proxy)$
      env:
        LOG_LEVEL: '${{ inputs.LOG_LEVEL }}'
        RENOVATE_GIT_PRIVATE_KEY: ${{ inputs.GPG_PRIVATE_KEY }}
        RENOVATE_RECREATE_WHEN: '${{ steps.vars.outputs.RECREATE_PRS }}'
        RENOVATE_REPOSITORIES: '${{ github.repository }}'
