name: 'Init'
description: 'Checkout branch, login to aws, ecr and ghcr'
inputs:
  BRANCH_NAME:
    description: 'branch to checkout'
    default: ''
  REPOSITORY:
    description: 'repository to checkout'
    default: ''
  FETCH_DEPTH:
    description: 'depth to fetch for checkout'
    default: '1'
  ROLE:
    description: 'aws role to be used'
    default: ''
  ECR_REPOSITORY:
    description: 'ecr repository to login to'
    default: ''
  GITHUB_TOKEN:
    description: 'github token used to auth to ghcr'
    default: ''
  GITHUB_ACTOR:
    description: 'github actor used to auth to ghcr and used for checking out if the default token isnt good enough'
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      if: inputs.BRANCH_NAME != ''
      with:
        ref: ${{ inputs.BRANCH_NAME }}
        fetch-depth: ${{ inputs.FETCH_DEPTH }}
        repository: ${{ inputs.REPOSITORY || github.repository }}
        token: ${{ inputs.GITHUB_TOKEN || github.token }}

    - id: role_name
      if: inputs.ROLE != ''
      shell: bash
      run: |
        echo "ROLE_NAME=$(echo "${{ inputs.ROLE }}" | cut -d/ -f2)" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials
      if: inputs.ROLE != ''
      uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
      with:
        aws-region: ap-southeast-2
        role-to-assume: ${{ inputs.ROLE }}
        role-session-name: GithubActions-${{ steps.role_name.outputs.role_name }}

    - name: Login to Amazon ECR
      if: inputs.ROLE != '' && inputs.ECR_REPOSITORY != ''
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

    - name: Login to GitHub Container Registry
      if: inputs.GITHUB_ACTOR != ''
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ghcr.io
        username: ${{ inputs.GITHUB_ACTOR }}
        password: ${{ inputs.GITHUB_TOKEN }}
