name: 'Backup all repositories'
on:
  # change branch to run in a pr
  # push:
  #   branches:
  #     - feature/make-backup-script-break
  schedule:
    # Our Recovery Point Objective (RPO) is four hours.
    # Back up every three hours to give us some extra breathing room on top of that.
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  backup-repos:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: ausaccessfed/workflows/.github/actions/init@main
        with:
          BRANCH_NAME: ${{ github.ref }}
          ROLE: ${{ secrets.ROLE }}

      - name: restore backup directory
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: tmp
          key: ${{ runner.os }}-backup-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-backup-

      - name: Backup
        run: |
          bash ./scripts/copy-repos.sh "${{ secrets.ALL_REPO_SCOPED_TOKEN }}" 2>&1 | tee /tmp/output.txt

      - name: Cache backup directory
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: tmp
          key: ${{ runner.os }}-backup-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-backup-

      - id: failure_check
        run: |
          echo "SUCCESS=true" >> $GITHUB_OUTPUT

      - uses: ausaccessfed/workflows/.github/actions/summarise@main
        if: always() && steps.failure_check.outputs.SUCCESS != 'true'
        with:
          OUTPUT_FILES: '/tmp/output.txt'
          ENABLE_ACTION_SUMMARY: true
          SLACK_WEBHOOK_URL: ${{ secrets.DEV_OPS_SLACK_URL }}
          TITLE: 'Repo backup failed!!!!'
          SUCCESS: 'failure'
