name: 'Backup all repositories'
on:
  # change branch to run in a pr
  # push:
  #   branches:
  #     - feature/reafactor-backup
  schedule:
    # Our Recovery Point Objective (RPO) is four hours.
    # Back up every three hours to give us some extra breathing room on top of that.
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  backup-repos:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: GithubActions-workflows-ci

      - name: restore backup directory
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: tmp
          key: ${{ runner.os }}-backup-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-backup-

      - name: Backup
        run: |
          bash ./scripts/copy-repos.sh "${{ secrets.ALL_REPO_SCOPED_TOKEN }}"

      - name: Cache backup directory
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: tmp
          key: ${{ runner.os }}-backup-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-backup-
