name: Build Docker Image
on:
  workflow_call:
    inputs:
      ecr_repository:
        required: true
        type: string
      app:
        required: true
        type: string
      event_name:
        required: true
        type: string
      default_branch:
        required: true
        type: string
      version_command:
        required: true
        type: string
      test_command:
        required: true
        type: string
      task_1:
        default: 'echo "no command"'
        type: string
      task_2:
        default: 'echo "no command"'
        type: string
      task_3:
        default: 'echo "no command"'
        type: string
      production_environments:
        required: true
        type: string
    secrets:
      DOCKER_ECR:
        required: true
      ROLE:
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    name: Build base
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - "3306:3306"
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        if: github.event_name == 'issue_comment'
        id: comment-branch

      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        if: github.event_name == 'issue_comment'
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          description: "testing, building and pushing image"
          context: "Dev federation deploy"

      - id: env1
        name: set envs
        run: |
          ## PR comment branch || pr branch || default branch
          if [ "${{ steps.comment-branch.outputs.head_ref }}" != "" ]; then
            branch_name="${{ steps.comment-branch.outputs.head_ref }}"
          elif [ "${{ github.head_ref }}" != "" ]; then
            branch_name="${{ github.head_ref }}"
          else
            branch_name="${{ github.ref_name }}"
          fi
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_OUTPUT

          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "ISSUE_COMMENT_HEAD_SHA=${{ steps.comment-branch.outputs.head_sha }}" >> $GITHUB_OUTPUT
            echo "GITHUB_SHA=${{ steps.comment-branch.outputs.head_sha }}" >> $GITHUB_OUTPUT
            image_tag=adhoc-${{steps.comment-branch.outputs.head_ref}}-${{steps.comment-branch.outputs.head_sha}}
          else
            image_tag=stable-${{ github.sha }}
            echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
          image_tag=$(echo "$image_tag" | tr / _)
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_OUTPUT

      - name: Create Cache Registry
        id: cache-docker-images
        uses: actions/cache@v2
        with:
          path: ${{ env.IMAGE_CACHE_DIR }}
          key: ${{ runner.os }}-docker-images-${{ steps.env1.outputs.GITHUB_SHA }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.env1.outputs.BRANCH_NAME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: GithubActions-${{ inputs.app }}-ci

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: set more envs
        id: env2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DOCKER_ECR=${{ secrets.DOCKER_ECR }}
          VERSION=$(${{ inputs.version_command }})
          BASE_IMAGE="${DOCKER_ECR}ruby-base:${VERSION}"
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_OUTPUT
          # Strip git ref prefix from version
          IMAGE_ID=$(echo "$ECR_REGISTRY/${{ inputs.ecr_repository }}" | tr '[A-Z]' '[a-z]')
          echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_OUTPUT
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_OUTPUT

      - name: Build Test OCI Image
        run: |
          docker pull $IMAGE_ID:cache || echo "true"
          DOCKER_BUILDKIT=1 docker build --target development \
          --build-arg BASE_IMAGE=${{ env.BASE_IMAGE }} \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from $IMAGE_ID:cache -t $IMAGE_ID:cache .

      - name: Ensure MySQL is ready
        if: inputs.test_command != ''
        timeout-minutes: 5
        run: |
          while ! mysqladmin ping -h"127.0.0.1" --silent; do
            sleep 1
          done

      - name: Run task 1
        run: |
          ${{ inputs.task_1 }}

      - name: Run task 2
        run: |
          ${{ inputs.task_2 }}

      - name: Run task 3
        run: |
          ${{ inputs.task_3 }}

      - name: Tests
        if: inputs.test_command != ''
        env:
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: password
          DATABASE_HOST: host.docker.internal
          PREPARE_DB: true
          RAILS_ENV: test
        run: |
          docker load --input ${{ env.IMAGE_CACHE_DIR }}/${{ env.IMAGE_CACHE_KEY }}.tar
          ${{ inputs.test_command }}

      - name: Build Production OCI Image
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from $IMAGE_ID:development \
          --build-arg BASE_IMAGE=${{ env.BASE_IMAGE }} \
          --build-arg RELEASE_VERSION=${IMAGE_TAG} \
          -t $IMAGE_ID:$IMAGE_TAG .

      - name: Push to ECR
        if: (github.event_name == 'push' && env.BRANCH_NAME == '${{ inputs.default_branch }}') || github.event_name == 'issue_comment'
        run: |
          docker load --input ${{ env.IMAGE_CACHE_DIR }}/${{ env.IMAGE_STABLE_KEY }}.tar
          docker push ${{ needs.build-base.outputs.IMAGE_ID }}:${{ needs.build-base.outputs.IMAGE_TAG }}

      - name: Push cache to ECR
        if: (github.event_name == 'push' && env.BRANCH_NAME == '${{ inputs.default_branch }}')
        run: |
          docker load --input ${{ env.IMAGE_CACHE_DIR }}/${{ env.IMAGE_CACHE_KEY }}.tar
          docker push ${{ inputs.app }}:cache

      - name: Update GitOps Repo to trigger deploys
        if: env.BRANCH_NAME == '${{ inputs.default_branch }}' && github.event_name == 'push'
        run: |
          printenv > .envs
           docker run --env-file .envs \
           -e PROJECTS="${{ inputs.app }}" \
           -e ENVIRONMENTS="${{ inputs.environments }}" \
           ${{ needs.build-base.outputs.ECR_REGISTRY }}/publish_app:latest

      - name: Update GitOps Repo to trigger deploys for development
        if: github.event_name == 'issue_comment'
        run: |
          printenv > .envs
           docker run --env-file .envs \
           -e PROJECTS="${{ inputs.app }}" \
           -e ENVIRONMENTS="development" \
           ${{ needs.build-base.outputs.ECR_REGISTRY }}/publish_app:latest

      - name: check for failures
        run: |
          output=
          if [ "${{ needs.run-tests.result }}" != "success"]; then 
            output="${output}Run tests failed! "
          fi

          if [ "${{ needs.run-task-1.result }}" != "success"]; then 
            output="${output}Run task 1 failed! "
          fi

          if [ "${{ needs.run-task-2.result }}" != "success"]; then 
            output="${output}Run task 2 failed! "
          fi

          if [ "${{ needs.run-task-3.result }}" != "success"]; then 
            output="${output}Run task 3 failed! "
          fi

          if [ "${{ needs.build-base.result }}" != "success"]; then 
            output="${output}build base failed! "
          fi

          if [ "${{ needs.build-production.result }}" != "success"]; then 
            output="${output}build production failed! "
          fi

          if [ "${{ needs.push-images.result }}" != "success"]; then 
            output="${output}push images failed!"
          fi

          status="failure"

          if [ "$output" == ""]; then 
            output="Manifest updated, Deploying to ${{ inputs.app }}.dev.aaf.edu.au (may take up to 5 minutes)"
            status="success"
          fi
          echo "ADHOC_OUTPUT=$output" >> $GITHUB_ENV
          echo "ADHOC_STATUS=$status" >> $GITHUB_ENV

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ needs.build-base.outputs.ISSUE_COMMENT_HEAD_SHA }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ env.ADHOC_STATUS }}
          targetUrl: https://${{ inputs.app }}.dev.aaf.edu.au
          description: ${{ env.ADHOC_OUTPUT }}
          context: "Dev federation deploy"
