name: Build Docker Image
on:
  workflow_call:
    inputs:
      ecr_repository:
        required: true
        type: string
      dev_url:
        required: true
        type: string
      event_name:
        required: true
        type: string
      event_comment_body:
        default: ""
        type: string
      default_branch:
        default: "master"
        type: string
      version_command:
        default: "cat .ruby-version"
        type: string
      production_build_task_1_name:
        default: "N/A"
        type: string
      production_build_task_1:
        default: ""
        type: string
      production_build_task_2_name:
        default: "N/A"
        type: string
      production_build_task_2:
        default: ""
        type: string
      production_build_task_3_name:
        default: "N/A"
        type: string
      production_build_task_3:
        default: ""
        type: string
      extra_task_1_name:
        default: "N/A"
        type: string
      extra_task_1:
        default: ""
        type: string
      extra_task_2_name:
        default: "N/A"
        type: string
      extra_task_2:
        default: ""
        type: string
      extra_task_3_name:
        default: "N/A"
        type: string
      extra_task_3:
        default: ""
        type: string
      production_environments:
        required: true
        type: string
    secrets:
      DOCKER_ECR:
        required: true
      ROLE:
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    name: run
    if: inputs.event_name != 'issue_comment' || (contains(inputs.event_comment_body, '/deploy')  && contains('phyzical,ArthurZheng,ritchiey,matthew-puku,rianniello,Kfoster14,waldofouche,Bo', github.event.author.login))
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - "3306:3306"
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        if: inputs.event_name == 'issue_comment'
        id: comment-branch

      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        if: inputs.event_name == 'issue_comment'
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          description: "testing, building and pushing image"
          context: "Dev federation deploy"

      - id: env1
        name: set envs
        run: |
          ## PR comment branch || pr branch || default branch
          if [ "${{ steps.comment-branch.outputs.head_ref }}" != "" ]; then
            branch_name="${{ steps.comment-branch.outputs.head_ref }}"
          elif [ "${{ github.head_ref }}" != "" ]; then
            branch_name="${{ github.head_ref }}"
          else
            branch_name="${{ github.ref_name }}"
          fi
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_OUTPUT

          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            image_tag=adhoc-${{steps.comment-branch.outputs.head_ref}}-${{steps.comment-branch.outputs.head_sha}}
          else
            image_tag=stable-${{ github.sha }}
          fi
          image_tag=$(echo "$image_tag" | tr / _)
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.env1.outputs.BRANCH_NAME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: GithubActions-${{ inputs.ecr_repository }}-ci

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: set more envs
        id: env2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          DOCKER_ECR=${{ secrets.DOCKER_ECR }}
          VERSION=$(${{ inputs.version_command }})
          BASE_IMAGE="${DOCKER_ECR}ruby-base:${VERSION}"
          echo "BASE_IMAGE=$BASE_IMAGE" >> $GITHUB_OUTPUT
          # Strip git ref prefix from version
          IMAGE_ID=$(echo "$ECR_REGISTRY/${{ inputs.ecr_repository }}" | tr '[A-Z]' '[a-z]')
          echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_OUTPUT
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_OUTPUT

      - name: Build Test OCI Image
        run: |
          docker pull ${{ steps.env2.outputs.IMAGE_ID }}:cache || echo "true"
          DOCKER_BUILDKIT=1 docker build --target development \
          --build-arg BASE_IMAGE=${{ steps.env2.outputs.BASE_IMAGE }} \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from ${{ steps.env2.outputs.IMAGE_ID }}:cache \
          -t ${{ steps.env2.outputs.IMAGE_ID }}:cache \
          -t app:cache .

      - name: Task ${{ inputs.extra_task_1_name }}
        if: inputs.extra_task_1 != ''
        run: |
          ${{ inputs.extra_task_1 }}

      - name: Task ${{ inputs.extra_task_2_name }}
        if: inputs.extra_task_2 != ''
        run: |
          ${{ inputs.extra_task_2 }}

      - name: Task ${{ inputs.extra_task_3_name }}
        if: inputs.extra_task_3 != ''
        run: |
          ${{ inputs.extra_task_3 }}

      - name: Build Production OCI Image
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from ${{ steps.env2.outputs.IMAGE_ID }}:cache \
          --build-arg BASE_IMAGE=${{ steps.env2.outputs.BASE_IMAGE }} \
          --build-arg RELEASE_VERSION=${{ steps.env1.outputs.IMAGE_TAG }} \
          -t ${{ steps.env2.outputs.IMAGE_ID }}:${{ steps.env1.outputs.IMAGE_TAG }} .

      - name: Task ${{ inputs.production_build_task_1_name }}
        if: inputs.production_build_task_1 != ''
        run: |
          ${{ inputs.production_build_task_1 }}

      - name: Task ${{ inputs.production_build_task_2_name }}
        if: inputs.production_build_task_2 != ''
        run: |
          ${{ inputs.production_build_task_2 }}

      - name: Task ${{ inputs.production_build_task_3_name }}
        if: inputs.production_build_task_3 != ''
        run: |
          ${{ inputs.production_build_task_3 }}

      - name: Push to ECR
        if: (github.event_name == 'push' && steps.env1.outputs.BRANCH_NAME == inputs.default_branch) || github.event_name == 'issue_comment'
        run: |
          docker push ${{ steps.env2.outputs.IMAGE_ID }}:${{ steps.env1.outputs.IMAGE_TAG }}

      - name: Push cache to ECR
        if: (github.event_name == 'push' &&  steps.env1.outputs.BRANCH_NAME == inputs.default_branch)
        run: |
          docker push ${{ steps.env2.outputs.IMAGE_ID }}:cache

      - name: Update GitOps Repo to trigger deploys
        if: steps.env1.outputs.BRANCH_NAME == inputs.default_branch && github.event_name == 'push'
        run: |
          printenv > .envs
           docker run --env-file .envs \
           -e PROJECTS="${{ inputs.ecr_repository }}" \
           -e IMAGE_TAG=${{ steps.env1.outputs.IMAGE_TAG }} \
           -e ENVIRONMENTS="${{ inputs.production_environments }}" \
           -e ECR_REPOSITORY="${{ inputs.ecr_repository }}" \
           ${{ steps.env2.outputs.ECR_REGISTRY }}/publish_app:latest

      - name: Update GitOps Repo to trigger deploys for development
        if: github.event_name == 'issue_comment'
        run: |
          printenv > .envs
           docker run --env-file .envs \
           -e PROJECTS="${{ inputs.ecr_repository }}" \
           -e IMAGE_TAG=${{ steps.env1.outputs.IMAGE_TAG }} \
           -e ENVIRONMENTS="development" \
           -e ECR_REPOSITORY="${{ inputs.ecr_repository }}" \
           ${{ steps.env2.outputs.ECR_REGISTRY }}/publish_app:latest

      - name: check for failures
        id: failure-check
        if: github.event_name == 'issue_comment' && always()
        run: |
          output=
          status="failure"
          if [ "${{ needs.run.result }}" != "success"]; then 
            output="${output}push images failed!"
          fi

          if [ "$output" == ""]; then 
            output="Manifest updated, Deploying to ${{ inputs.dev_url }} (may take up to 5 minutes)"
            status="success"
          fi
          echo "ADHOC_OUTPUT=$output" >> $GITHUB_OUTPUT
          echo "ADHOC_STATUS=$status" >> $GITHUB_OUTPUT

      - name: Set final commit status
        if: github.event_name == 'issue_comment' && always()
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ steps.failure-check.outputs.ADHOC_STATUS }}
          targetUrl: ${{ inputs.dev_url }}
          description: ${{ steps.failure-check.outputs.ADHOC_OUTPUT }}
          context: "Dev federation deploy"
