name: 'Renovate Dependency Check'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'
jobs:
  renovate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ${{ fromJSON(vars.RENOVATE_REPOSITORIES) }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Renovate
        uses: renovatebot/github-action@5d3fbef92a76cbf78f5732d17c07a2e76e6f7555 # v39.1.4
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.ALL_REPO_SCOPED_TOKEN }}
        env:
          LOG_LEVEL: 'info'
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.RENOVATE_GPG_PRIVATE_KEY }}
          RENOVATE_REPOSITORIES: '["${{ matrix.repository }}"]'
