name: 'Renovate Dependency Check'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'
jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Renovate
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.ALL_REPO_SCOPED_TOKEN }}
        env:
          LOG_LEVEL: 'info'
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.RENOVATE_GPG_PRIVATE_KEY }}
          RENOVATE_REPOSITORIES: '["ausaccessfed/discovery-service","ausaccessfed/ecr-retagger","ausaccessfed/federationmanager","ausaccessfed/idp","ausaccessfed/image-scanner","ausaccessfed/kubeval-tools","ausaccessfed/lambda-promtail","ausaccessfed/metadata-distribution","ausaccessfed/oidc_relying_party_example","ausaccessfed/publish_app","ausaccessfed/puppeteer-tester","ausaccessfed/rapid-connector","ausaccessfed/rapid-idp-manager","ausaccessfed/reporting-service","ausaccessfed/ruby-base","ausaccessfed/shib-sp","ausaccessfed/validator-service","ausaccessfed/verifid","ausaccessfed/workflows"]'
          # RENOVATE_REPOSITORIES: '${{ vars.RENOVATE_REPOSITORIES }}'
          # "ausaccessfed/aaf-terraform",
