name: 'Renovate Dependency Check'
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: false
        type: choice
        options:
          - 'ausaccessfed/aaf-terraform'
          - 'ausaccessfed/discovery-service'
          - 'ausaccessfed/ecr-retagger'
          - 'ausaccessfed/federationmanager'
          - 'ausaccessfed/idp'
          - 'ausaccessfed/image-scanner'
          - 'ausaccessfed/kubeval-tools'
          - 'ausaccessfed/lambda-promtail'
          - 'ausaccessfed/oidc_relying_party_example'
          - 'ausaccessfed/publish_app'
          - 'ausaccessfed/puppeteer-tester'
          - 'ausaccessfed/rapid-connector'
          - 'ausaccessfed/rapid-idp-manager'
          - 'ausaccessfed/reporting-service'
          - 'ausaccessfed/ruby-base'
          - 'ausaccessfed/shib-sp'
          - 'ausaccessfed/validator-service'
          - 'ausaccessfed/verifid'
          - 'ausaccessfed/workflows'
          - 'ausaccessfed/rapid-idp-2step-auth'
          - 'ausaccessfed/rapid-idp-discovery'
          - 'ausaccessfed/rapid-idp-eduperson-attributes'
          - 'ausaccessfed/rapid-idp-login-module'
      forceRecreate:
        description: 'If you should crecreate all prs (this is break glass)'
        type: boolean
        required: false
        default: false
      logLevel:
        description: 'Log level'
        type: choice
        default: 'info'
        options:
          - info
          - debug
  schedule:
    - cron: '0 */12 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: ausaccessfed/workflows/.github/actions/init@main
        with:
          BRANCH_NAME: 'main'
          ROLE: ${{ secrets.ROLE }}

      - name: vars
        id: vars
        run: |
          RECREATE_PRS=$([ "${{ inputs.forceRecreate }}" == "true" ] && echo "always" || echo "auto")
          echo "RECREATE_PRS=$RECREATE_PRS" >> $GITHUB_OUTPUT

          LOG_LEVEL=$([ "${{ inputs.logLevel }}" == "" ] && echo "info" || echo "${{ inputs.logLevel }}")
          echo "LOG_LEVEL=$LOG_LEVEL" >> $GITHUB_OUTPUT

          REPOSITORIES=$([ "${{ inputs.repository }}" != "" ] && echo '["${{ inputs.repository }}"]' || echo '${{vars.RENOVATE_REPOSITORIES}}' )
          echo "REPOSITORIES=$REPOSITORIES" >> $GITHUB_OUTPUT

      - name: Renovate
        uses: renovatebot/github-action@630a255a1f2f56c8d8ce160bed3e3ca577ca53e2 # v40.2.7
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.ALL_REPO_SCOPED_TOKEN }}
          env-regex: ^(?:RENOVATE_\w+|AWS_\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|(?:HTTPS?|NO)_PROXY|(?:https?|no)_proxy)$
        env:
          LOG_LEVEL: '${{ steps.vars.outputs.LOG_LEVEL }}'
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.RENOVATE_GPG_PRIVATE_KEY }}
          RENOVATE_RECREATE_WHEN: '${{ steps.vars.outputs.RECREATE_PRS }}'
          RENOVATE_REPOSITORIES: '${{ steps.vars.outputs.REPOSITORIES }}'
