name: Sync development
on:
  workflow_call:
    inputs:
      ecr_repository:
        required: true
        type: string
      app:
        required: true
        type: string
      sha:
        required: true
        type: string
    secrets:
      ROLE:
        required: true

jobs:
  sync:
    name: Deploy trunk to development
    runs-on: ubuntu-latest
    steps:
      - uses: ausaccessfed/workflows/.github/actions/publish_app@main
        with:
          ROLE: ${{ secrets.ROLE }}
          ECR_REPOSITORY: ${{ inputs.ecr_repository }}
          PUBLISH_IMAGE_TAG: stable-${{ inputs.sha }}
          PUBLISH_APPS: ${{ inputs.app }}
          PUBLISH_ENVIRONMENTS: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          IS_ADHOC: 'true'
