name: 'test'
on:
  push:
jobs:
  renovate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ${{ vars.RENOVATE_REPOSITORIES }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: test
        run: echo '["${{ matrix.repository }}"]'
