name: Todo processor
on:
  push:
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_REF:
        description: 'The SHA of the commit to get the diff for'
        required: true
      MANUAL_BASE_REF:
        description: 'By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here'
        required: false
jobs:
  todo_processor:
    runs-on: ubuntu-latest
    name: 'TODO Processing'
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: ausaccessfed/workflows/.github/actions/todo-processor@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.RENOVATE_GPG_PRIVATE_KEY }}
          MANUAL_COMMIT_REF: ${{ inputs.MANUAL_COMMIT_REF }}
          MANUAL_BASE_REF: ${{ inputs.MANUAL_BASE_REF }}
