name: Todo processor
on:
  workflow_dispatch:
jobs:
  todo_processor:
    runs-on: ubuntu-latest
    name: 'TODO Processing'
    permissions: write-all
    steps:
      - uses: ausaccessfed/workflows/.github/actions/todo-processor@feature/testing-todo-workflow
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO: this is a test does it work!!
          # TODO: Yes it does
