name: Todo processor
on:
  push:
jobs:
  todo_processor:
    runs-on: ubuntu-latest
    name: 'TODO Processing'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: ausaccessfed/workflows/.github/actions/todo-processor@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
